### ISSUE TITLE
PrivacyPortal looks interesting

### ISSUE THREAD

**Issue by anderspitman** [privacyportal/client#36]
Heyo, sorry if there's a better place for this.

Just heard about you via https://github.com/LemmyNet/lemmy/pull/4881

PrivacyPortal looks really cool. Similar in many ways to my project [LastLogin](https://lastlogin.net/). I especially like that you've integrated email support. Do you support/plan to support WebFinger+OIDC, the way [Tailscale uses it](https://tailscale.com/kb/1240/sso-custom-oidc)?

I'm hoping that someday LastLogin doesn't need to exist, at least as a centralized service, because I want things to move towards individuals controlling their own IdPs on their own domain. However, some (most?) people will never do that no matter how easy it is, so I think services like PrivacyPortal and [Hellō](https://www.hello.coop/) will always be useful. Also, as you mention in your FAQ, individual IdPs enable a level of tracking.

**Comment by privacyguard** [comment]
@anderspitman thank you for reaching out and forgive our delay. For general questions / feature requests, you can contact our support directly via email or use the built-in support in the Privacy Portal app. That way we can respond within 24h.

Concerning your question about `WebFinger+OIDC`, we looked into this use case. While we love decentralization, the current flow does not seem to align with the strict privacy goals we have set for our users. Here's why:

1. Users logging in using custom domains risk exposing their identities (since it's tied to the custom domain). Our approach aims to group all users under a single domain to provide better privacy.
2. During the sign-up/in  process, the user has to provide their email address to the application (OIDC client). Then Privacy Portal would have to provide that same address in the `userinfo` request. Our privacy policy prevents us from exposing the user's real email address to any third party. One of our goals it to ensure every email address is a unique single-purpose alias to prevent tracking.
3. The WebFinger configuration requires including the real email address as part of the WebFinger response which means the email address becomes public and subject to spam.

Our goals in creating the Privacy Portal Identity Provider is to provide strict and infallible privacy protection for users. By Signing In with Privacy Portal, users can be assured that no personal information was gathered during the login process. At the same time, by adopting our provider, websites can prove to their users that they're not in the business of collecting personal information (at least not from the authentication process).

Please let us know if we missed something.

--Privacy Portal Support

**Comment by privacyguard** [comment]
We will be closing this issue since it's been stale for a while. Please contact our support directly for further discussions if needed. Thank you!

**Comment by anderspitman** [comment]
Sorry, I forgot to respond to this. I don't have any problem with closing the issue. Thanks for your answers and good luck with PrivacyPortal!
